### ISSUE TITLE
Item duplication in the Edit Results window

### ISSUE THREAD

**Issue by Lknechtli** [stringandstickytape/RegulatedNoise#13]
When importing stuff the the OCR, duplication commonly appears if you click into the Edit Results window.

**Comment by stringandstickytape** [comment]
There is code to do this... but it's not working and needs fixing :/

**Comment by Lknechtli** [comment]
i think the larger issue is - where are the duplicates coming from anyways? I've had a single screenshot generate multiples of the same item.

**Comment by stringandstickytape** [comment]
Never seen that, I've only seen duplication from overlapping screenshots...? Code to fix that doesn't seem to be working at the moment.

**Comment by Lknechtli** [comment]
I'll see if I can reproduce once I get my computer working again...

**Comment by stringandstickytape** [comment]
Fixed in the next version.
