### ISSUE TITLE
No way to clear ORC corrections if you don't want to import

### ISSUE THREAD

**Issue by Lknechtli** [stringandstickytape/RegulatedNoise#14]
The only way to not import something once you've scanned it in (IE you accidentally put a bad station name in) is to close the application and reopen it.

**Comment by stringandstickytape** [comment]
Do you mean a "Clear "CSV Output from OCR"" button?

**Comment by Lknechtli** [comment]
something like that yes. 
For clarity, you might also want to add a button next to the import button which says "skip", instead of having the user blank out the field

**Comment by stringandstickytape** [comment]
Would an "Abandon" button under the "Import" button do the trick, or am I missing the point here?

**Comment by stringandstickytape** [comment]
Also, note that if the station name is wrong, you can change it in the box above the corrections window, and it will auto-update in the CSV output.

**Comment by Lknechtli** [comment]
Maybe change "Import" to "Save" or "Save Data" and add a "Clear" or "Clear Data" button?

Also, I know that you can usually change the station name, but I've had instances where it only changes it for part of the current list, so adding a clear data button would act as a catch all for bad OCR.

**Comment by Lknechtli** [comment]
But yes, you have the right idea.

**Comment by stringandstickytape** [comment]
haha, I've just realised how "I've had instances where it only changes it for part of the current list" is indeed possible :/

**Comment by Lknechtli** [comment]
Hooray! I've a mind to fork and see if I can make some other improvements.

**Comment by stringandstickytape** [comment]
Please do!  The more the merrier!! :)

**Comment by stringandstickytape** [comment]
Fixed in the next version :)
