### ISSUE TITLE
Automatic OCR calibration doesn't quite work (screenshots included)

### ISSUE THREAD

**Issue by Lknechtli** [stringandstickytape/RegulatedNoise#18]
Using automatic calibration with 1920x1080 resolution results in the application attempting to OCR the line between the labels of the table and the commodities.  It also does not know where to find the station name.

zip file with screenshots used:
http://1drv.ms/1FJ6s5P

**Comment by stringandstickytape** [comment]
Calibration pretty-much competely rewritten, so closing.  Please open a new one if there are problems with... the new one. :)
