### ISSUE TITLE
OCR Auto Calib knock out default 

### ISSUE THREAD

**Issue by Drahnier016** [stringandstickytape/RegulatedNoise#19]
Auto OCR tested and doesnt work well.
So when i try to recalibait with my previous setting it doesnt work to
so atm i cant use this tool couse no prices or supply are recordet for some reason.
What i get is just all commoditys name, nothing else.

sorry for bad english :P

**Comment by stringandstickytape** [comment]
What resolution are you running at?

**Comment by Drahnier016** [comment]
1080p

Update: after delet the files and unpack the zip again and calibrate it works.

**Comment by stringandstickytape** [comment]
Thanks for the update.  In v1.8, calibration pretty-much competely rewritten, so closing anyway. Please open a new one if there are problems with v1.8.
