### ISSUE TITLE
v1.73 wont start 

### ISSUE THREAD

**Issue by sutex** [stringandstickytape/RegulatedNoise#20]
Dump file https://www.dropbox.com/s/t0sfwd21jfs4fcu/RegulatedNoiseDump.dmp?dl=0

UPDATE 
IMPORTANT I disable this & now 1.73 is working , Windows Media Player Network Sharing Service & WLAN AutoConfig
Had a issue with my Bonic (seti) PC that's networked though router ,stuff around in services , yesterday, that night play ED with ver 1.7 all good

Shutdown next day install 1.73 wont star, then tried , 1.72 1.7 & 1.5 Even did clean install reboot, nothing worked until I did the above,, weird or what

**Comment by stringandstickytape** [comment]
IMPORTANT I disable this & now 1.73 is working , Windows Media Player Network Sharing Service & WLAN AutoConfig
Had a issue with my Bonic (seti) PC that's networked though router ,stuff around in services , yesterday, that night play ED with ver 1.7 all good

Shutdown next day install 1.73 wont star, then tried , 1.72 1.7 & 1.5 Even did clean install reboot, nothing worked until I did the above,, weird or what

**Comment by stringandstickytape** [comment]
Yep, that's as weird as all hell.  

Thanks for the dump file - I can see that it crashed when trying to read your DisplaySettings.xml - "There is an error in XML document (7, 3)." at LoadDisplaySettings => Display = (EdDisplayConfig)serializer.Deserialize(myFileStream); .

No idea what it means.  Let's see if the problem recurs in v1.8 - if it does, see if you can grab a copy of your DisplaySettings.xml and attach it to the issue.

**Comment by sutex** [comment]
No the problem did not happen in ver 1.8 but then again Windows Media Player Network Sharing Service is still disable

**Comment by stringandstickytape** [comment]
OK.  I'll close this for the time being; if it does it again, please grab the DisplaySettings.xml file as soon as you can after the crash, and we'll reopen it.

Thanks for the feedback again, sutex, keep it coming!

**Comment by sutex** [comment]
Yep just found this , so many tabs ,Ok all good with 1.82,  but more suggestion :)
