### ISSUE TITLE
Price Analysis "By Station

### ISSUE THREAD

**Issue by Drahnier016** [stringandstickytape/RegulatedNoise#26]
I dont know if its a bug but in the Tab"By Station" if i click on Dropdown menu the stationnames arent sortet alphabetical its very hard to find the right station when there are listed ouver 700 Stations.

If there is a reason why this tab is not alphabetical pls let me know otherwise  it would be great when it can be fixet to alphabetical or just implement an Serch function.

**Comment by stringandstickytape** [comment]
It's sorted by distance from your current location. Does that help?

**Comment by Drahnier016** [comment]
ah ok that´s it ty.
