### ISSUE TITLE
Data seems not to be always properly updated after OCR in 1.5

### ISSUE THREAD

**Issue by TarrX** [stringandstickytape/RegulatedNoise#3]
I've imported old data from EliteOCR by CSV and then revisited the system a couple of times. After a while I decided to update the prices with new screenshots. While the Screenshots are properly scanned and the data looks OK in the csv before Import, the database seems not to be updated for at least one commodity, Performance Enhancers used to be 7531, now are at 7453 in the scan, but not imported. 7531 is also the price of Progenitor Cells on the next row, which may be related. It may also be related to a possible missing last import timestamp from the old data or somesuch?

**Comment by stringandstickytape** [comment]
It takes its timestamp from the screenshot file itself (the Date Creation time).  Does that explain what you're seeing?

**Comment by TarrX** [comment]
No. I've done some experimentation and it was quite confusing. It also may be a general view update issue, as I deleted the affected rows, made new screenshots, ocr and then I did not see the new data at all or only partially. After a restart things seemed to be ok.

This also seems to affect the Station-To-Station Tab, after an ocr run of already existing system data the whole tab seems to not work properly, issues ranging from having to re-select to restart.

**Comment by stringandstickytape** [comment]
Hm, that's odd.  It seemed to work last time I updated prices.

"After a restart things seemed to be ok."

Do you mean that when you restarted the app, you saw the data you were expecting to see (correctly updated) before you restarted the app?  Or do you mean that when you tried updating _after_ restarting the app, it worked OK?

If you toggle the "Only include stations within" checkbox, it will completely redraw the UI according to the current dataset, which could flush out any errors.  Try hitting that and seeing if it makes data appear correctly, next time the problem shows up.  Let me know what you find.

**Comment by TarrX** [comment]
I mean I imported the OCR result, then restarted the App and it looked fine. I'll try the other in a while, once the data has changed.

**Comment by TarrX** [comment]
Did some testing and it seems the issue is with the Station-To-Station Tab, I have my route active and import data from ocr for one of the stations and it doesn't show up. Clicking "Only include" doesn't help it seems. In 'By Station' it looked ok, this time but changing back I had to first select a different route and then my original one to see the new data.

**Comment by stringandstickytape** [comment]
Haha, I think I have found it.  I'll leave this issue open for the time being, I'm not certain :)

Good pointers in the bug report, btw :+1:

**Comment by stringandstickytape** [comment]
Seems this is fixed, closing.  We can re-open if necessary.
