### ISSUE TITLE
Fatal error when changing Products location in v1.81 config

### ISSUE THREAD

**Issue by boloniusMonk** [stringandstickytape/RegulatedNoise#43]
The application launches with the default settings for ProductsPath and GamePath, but has a fatal error & dump if you change them.  This did not happen in 1.8.

dump file: https://www.dropbox.com/s/drt3bdp5b1b2pgo/RegulatedNoiseDump.dmp?dl=0

update: It launched after I logged into the game and the log file was updated.  1.8 launched but showed no location while 1.81 had the error.  Now both start and show the location.

update2: I still get the error again when I try to open the app without being in game.

**Comment by stringandstickytape** [comment]
Hm.  Actually it's b0rking while trying to read your log file to find the
system name.  Could you try running the game again, then starting RN and
seeing if it happens again - and if it does, grab a copy of your netlog
file and post it please? :)

**Comment by stringandstickytape** [comment]
b0rking while trying to read the lines in reverse, code which did change in
1.81

**Comment by boloniusMonk** [comment]
I can't seem to replicate it.  I will post the latest log file if it happens again.  I am guessing it was a new log file with no system data in it.

**Comment by stringandstickytape** [comment]
Not sure...keep an eye on it, it might need a very specific (seemingly
random) set of circumstances.

**Comment by stringandstickytape** [comment]
Hm.  Staring at the code, it seems like it ought to fail like this if it
finds a line in the log that's longer than 1000 characters, but only if
that line is lower in the file (more recent) than the most recent "current
system" line.  That's just in theory, but it's how the code seems to
read... :-/

**Comment by boloniusMonk** [comment]
It would be the line in the log file that lists friends.  Mine is around 5000 characters long.

`<data><users><item><user_id>5543</user_id><commander_id></commander_id><name>417661746172</name><isDocked>0</isDocked><pending>0</pending><lastLocation>Offline</lastLocation><presence>offline</presence><solo></solo><privateGroup_id></privateGroup_id><canAccept>0</canAccept><ignored>0</ignored></item><item> etc.....`

edit: deleting that line from the logs doesn't fix it though.  It still dumps, but maybe this one shows a different error: https://www.dropbox.com/s/lqhyu61uoe3di6z/2.RegulatedNoiseDump.dmp?dl=0.   I would guess problem 1 is the long line, then problem 2 is there is no location in the new log file until I login.

**Comment by stringandstickytape** [comment]
ahhhhhhhhhhhhhh i think that would do it...

**Comment by stringandstickytape** [comment]
Seems to be working now.
