### ISSUE TITLE
Two Crashes 2  version 

### ISSUE THREAD

**Issue by sutex** [stringandstickytape/RegulatedNoise#45]
https://www.dropbox.com/s/31o7l6e4o1nobjh/VER%201.73%20RegulatedNoiseDump.dmp?dl=0

https://www.dropbox.com/s/x4bhyenoqotdlce/VER%201.81%20RegulatedNoiseDump.dmp?dl=0

**Comment by stringandstickytape** [comment]
Had a look at the v1.81 dump - same "There is an error in XML document
(7,3)" that we saw before.  Can you upload a copy
of "C:\Users\Philip\AppData\Local\Frontier Developments\Elite
Dangerous\Options\Graphics\DisplaySettings.xml" please?  It was that file
it was parsing, when it crashed...

**Comment by sutex** [comment]
The file Display Settings  , https://www.dropbox.com/s/ngob75fmlceg3cz/DisplaySettings.xml?dl=0
Just copy an pasted over the New ver 1.82 , it's working ,,:)
